# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fog.proto',
  package='fogapi',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tfog.proto\x12\x06\x66ogapi\"\x15\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\"(\n\x0b\x43oordinates\x12\x0b\n\x03lat\x18\x01 \x02(\x05\x12\x0c\n\x04long\x18\x02 \x02(\x05\"I\n\x0cRequestFetch\x12\x0f\n\x07imageId\x18\x01 \x02(\x05\x12(\n\x0b\x63oordinates\x18\x02 \x02(\x0b\x32\x13.fogapi.Coordinates\"$\n\rResponseFetch\x12\x13\n\x0bimageIdList\x18\x01 \x03(\x05\x32>\n\x06\x46ogAPI\x12\x34\n\x05\x46\x65tch\x12\x14.fogapi.RequestFetch\x1a\x15.fogapi.ResponseFetch')
)




_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='fogapi.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='fogapi.Error.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=42,
)


_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='fogapi.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='fogapi.Coordinates.lat', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long', full_name='fogapi.Coordinates.long', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=84,
)


_REQUESTFETCH = _descriptor.Descriptor(
  name='RequestFetch',
  full_name='fogapi.RequestFetch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='fogapi.RequestFetch.imageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='fogapi.RequestFetch.coordinates', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=159,
)


_RESPONSEFETCH = _descriptor.Descriptor(
  name='ResponseFetch',
  full_name='fogapi.ResponseFetch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageIdList', full_name='fogapi.ResponseFetch.imageIdList', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=197,
)

_REQUESTFETCH.fields_by_name['coordinates'].message_type = _COORDINATES
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['RequestFetch'] = _REQUESTFETCH
DESCRIPTOR.message_types_by_name['ResponseFetch'] = _RESPONSEFETCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:fogapi.Error)
  ))
_sym_db.RegisterMessage(Error)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:fogapi.Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)

RequestFetch = _reflection.GeneratedProtocolMessageType('RequestFetch', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTFETCH,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:fogapi.RequestFetch)
  ))
_sym_db.RegisterMessage(RequestFetch)

ResponseFetch = _reflection.GeneratedProtocolMessageType('ResponseFetch', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFETCH,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:fogapi.ResponseFetch)
  ))
_sym_db.RegisterMessage(ResponseFetch)



_FOGAPI = _descriptor.ServiceDescriptor(
  name='FogAPI',
  full_name='fogapi.FogAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=199,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='fogapi.FogAPI.Fetch',
    index=0,
    containing_service=None,
    input_type=_REQUESTFETCH,
    output_type=_RESPONSEFETCH,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOGAPI)

DESCRIPTOR.services_by_name['FogAPI'] = _FOGAPI

# @@protoc_insertion_point(module_scope)
