# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cloud.proto',
  package='cloudapi',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63loud.proto\x12\x08\x63loudapi\"\x15\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\"(\n\x0b\x43oordinates\x12\x0b\n\x03lat\x18\x01 \x02(\x05\x12\x0c\n\x04long\x18\x02 \x02(\x05\"L\n\x12RequestRegisterFog\x12*\n\x0b\x63oordinates\x18\x01 \x02(\x0b\x32\x15.cloudapi.Coordinates\x12\n\n\x02ip\x18\x02 \x02(\t\"7\n\x13ResponseRegisterFog\x12\x10\n\x08regionId\x18\x01 \x02(\x05\x12\x0e\n\x06ipList\x18\x02 \x03(\t\".\n\nRequestTag\x12\x0f\n\x07imageId\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\"K\n\x0cRequestFetch\x12\x0f\n\x07imageId\x18\x01 \x02(\x05\x12*\n\x0b\x63oordinates\x18\x02 \x02(\x0b\x32\x15.cloudapi.Coordinates\"$\n\rResponseFetch\x12\x13\n\x0bimageIdList\x18\x01 \x03(\x05\x32\xc2\x01\n\x08\x43loudAPI\x12N\n\x0fRegisterFogNode\x12\x1c.cloudapi.RequestRegisterFog\x1a\x1d.cloudapi.ResponseRegisterFog\x12,\n\x03Tag\x12\x14.cloudapi.RequestTag\x1a\x0f.cloudapi.Error\x12\x38\n\x05\x46\x65tch\x12\x16.cloudapi.RequestFetch\x1a\x17.cloudapi.ResponseFetch')
)




_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='cloudapi.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='cloudapi.Error.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=46,
)


_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='cloudapi.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='cloudapi.Coordinates.lat', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long', full_name='cloudapi.Coordinates.long', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=88,
)


_REQUESTREGISTERFOG = _descriptor.Descriptor(
  name='RequestRegisterFog',
  full_name='cloudapi.RequestRegisterFog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='cloudapi.RequestRegisterFog.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='cloudapi.RequestRegisterFog.ip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=166,
)


_RESPONSEREGISTERFOG = _descriptor.Descriptor(
  name='ResponseRegisterFog',
  full_name='cloudapi.ResponseRegisterFog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regionId', full_name='cloudapi.ResponseRegisterFog.regionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipList', full_name='cloudapi.ResponseRegisterFog.ipList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=223,
)


_REQUESTTAG = _descriptor.Descriptor(
  name='RequestTag',
  full_name='cloudapi.RequestTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='cloudapi.RequestTag.imageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='cloudapi.RequestTag.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=271,
)


_REQUESTFETCH = _descriptor.Descriptor(
  name='RequestFetch',
  full_name='cloudapi.RequestFetch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='cloudapi.RequestFetch.imageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='cloudapi.RequestFetch.coordinates', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=348,
)


_RESPONSEFETCH = _descriptor.Descriptor(
  name='ResponseFetch',
  full_name='cloudapi.ResponseFetch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageIdList', full_name='cloudapi.ResponseFetch.imageIdList', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=386,
)

_REQUESTREGISTERFOG.fields_by_name['coordinates'].message_type = _COORDINATES
_REQUESTFETCH.fields_by_name['coordinates'].message_type = _COORDINATES
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['RequestRegisterFog'] = _REQUESTREGISTERFOG
DESCRIPTOR.message_types_by_name['ResponseRegisterFog'] = _RESPONSEREGISTERFOG
DESCRIPTOR.message_types_by_name['RequestTag'] = _REQUESTTAG
DESCRIPTOR.message_types_by_name['RequestFetch'] = _REQUESTFETCH
DESCRIPTOR.message_types_by_name['ResponseFetch'] = _RESPONSEFETCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.Error)
  ))
_sym_db.RegisterMessage(Error)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)

RequestRegisterFog = _reflection.GeneratedProtocolMessageType('RequestRegisterFog', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREGISTERFOG,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.RequestRegisterFog)
  ))
_sym_db.RegisterMessage(RequestRegisterFog)

ResponseRegisterFog = _reflection.GeneratedProtocolMessageType('ResponseRegisterFog', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEREGISTERFOG,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.ResponseRegisterFog)
  ))
_sym_db.RegisterMessage(ResponseRegisterFog)

RequestTag = _reflection.GeneratedProtocolMessageType('RequestTag', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTTAG,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.RequestTag)
  ))
_sym_db.RegisterMessage(RequestTag)

RequestFetch = _reflection.GeneratedProtocolMessageType('RequestFetch', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTFETCH,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.RequestFetch)
  ))
_sym_db.RegisterMessage(RequestFetch)

ResponseFetch = _reflection.GeneratedProtocolMessageType('ResponseFetch', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFETCH,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloudapi.ResponseFetch)
  ))
_sym_db.RegisterMessage(ResponseFetch)



_CLOUDAPI = _descriptor.ServiceDescriptor(
  name='CloudAPI',
  full_name='cloudapi.CloudAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=389,
  serialized_end=583,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterFogNode',
    full_name='cloudapi.CloudAPI.RegisterFogNode',
    index=0,
    containing_service=None,
    input_type=_REQUESTREGISTERFOG,
    output_type=_RESPONSEREGISTERFOG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Tag',
    full_name='cloudapi.CloudAPI.Tag',
    index=1,
    containing_service=None,
    input_type=_REQUESTTAG,
    output_type=_ERROR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='cloudapi.CloudAPI.Fetch',
    index=2,
    containing_service=None,
    input_type=_REQUESTFETCH,
    output_type=_RESPONSEFETCH,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUDAPI)

DESCRIPTOR.services_by_name['CloudAPI'] = _CLOUDAPI

# @@protoc_insertion_point(module_scope)
